# URL structure: 
# /en/about-me/ (redirect from stdout.be, serves as homepage)
# /en/latest/
# /en/highlights/

settings:
    root:
        context: '../writing'
        assets: '.'

# doesn't work yet
defaults:
    language: 'en'

# doesn't work yet either
globals:
    shortlinks:
        context: 'nginx.shortlinks'

routes:
    assets:
        route: 'assets'
        context: 'assets'
        pipes:
            - list-files
        output:
            - copy-assets
    pages:
        route: '{language}/{permalink}/'
        layout: '{layout}'
        context: 'pages/{language}/{permalink}'
    posts:
        route: '{year}/{month}/{day}/{permalink}/'
        layout: '{layout}.detail'
        context: '2011/{layout}/{month}-{day}-{permalink}' # {year:d}
        defaults:
            layout: 'posts.detail'
            year: '2011'
        pipes:
            - gather-context
            - ./pipes/add-metadata
        output:
            - add-helpers
            - ./pipes/add-helpers
            - render-from-template
    # split up in en, nl en dan verschillende feeds voor categorieën.
    feed.all: 
        route: 'feeds/all.atom'
        layout: 'feed'
        defaults:
            title: 'Alle blogposts van stdout.be'
            type: 'all'
        output:
            - add-helpers
            - ./pipes/add-feed-helpers
            - render-from-template            
    feed.en:
        route: 'feeds/en.atom'
        layout: 'feed'
        defaults:
            title: 'English blogposts on stdout.be'
            type: 'en'
        output:
            - add-helpers
            - ./pipes/add-feed-helpers
            - render-from-template 
    feed.nl:
        route: 'feeds/nl.atom'
        layout: 'feed'
        defaults:
            title: 'Nederlandstalige blogposts op stdout.be'
            type: 'nl'
        output:
            - add-helpers
            - ./pipes/add-feed-helpers
            - render-from-template 
    feed.opennews:
        route: 'feeds/opennews.atom'
        layout: 'feed'
        defaults:
            title: 'Blogposts about Knight-Mozilla OpenNews on stdout.be'
            type: 'opennews'
        output:
            - add-helpers
            - ./pipes/add-feed-helpers
            - render-from-template 

todo2:
    media:
        # TODO: doesn't currently work w/ placeholders, 
        # so I think what I'll do is I'll keep this route out of Hector
        # for now and instead have NGINX fix it.
        # 
        # two thoughts: (1) we might need cross-slash placeholders
        # at some point like {permalink*} or even regex/surlex ones like {permalink=.+}
        # (2) maybe it might be interesting to "generalize" the "layout" concept
        # and allow certain pipes to "register" that they're able to handle
        # certain kinds of files? Probably not the right idea, but I want to think about
        # how we can make the pipes concept as great as possible.
        # 
        # route: 'images/content/{year}-{permalink}'
        # context: '{year}/media/{permalink}'
        route: 'images/content/2010'
        context: '../writing/2010/media'
        pipes:
            - list-files
        output:
            - copy-assets